#!/bin/sh

# Takes a single file arg, and for each gettext call it spits out:
# .pot file formatted strings,
#
# #: path/to/file:lineno
# msgid "A string shorter than 78 characters."
# msgstr ""
#
# #: path/to/file:lineno
# msgid ""
# "Multi line strings for lines longer than 78 characters, "
# "following normal conventions."
# msgstr ""
#

shout() { echo "$0: $*" >&2; }
die() { shout "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }


## vars

SRCFILE="${1:?Needs a target file as first argument.}"
# number of lines following gettext call to rip through
BLOCKSEARCH=${BLOCKSEARCH:-10}

## action

# start with a grep through the file,

try grep -Rn 'gettext' "$SRCFILE" | while read line ; do

  _printlineno() {
  # print path/to/file:lineno
  printf "#: "
  echo "$line" | try awk '{print $1}' | try sed 's#^\./##;s/:$//'
  }

  _lineno="`echo "$line" | cut -d ':' -f 2`"
  _lineblock=$(( _lineno + $BLOCKSEARCH ))
  echo "##############################################################################"

  # prints from line no, to blocksearch count
  try sed "${_lineno},${_lineblock}!d" "$SRCFILE" \
  | try awk -F 'gettext' '{print $2}' \
  | try grep . \
  | while read l2 ; do

      if [ "`echo "$l2" | grep '^("'`"  ] ; then
        _printlineno
        echo "#### DOUBLE"
        echo "$l2" \
        | sed 's/^("/"/' | sed 's#").*#"#'
        echo 
      elif [ "`echo "$l2" | grep "^('"`" ] ; then
        _printlineno
        echo "#### SINGLE"
        echo $l2
      else
        _printlineno
        echo "#### NONE"
        echo $l2
      fi

    done

  #echo 'msgid ""'
  echo 'msgstr ""'
  echo ''
done

true
